# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
